### PR TITLE
Force update progress on test state change

### LINKED ISSUE #72: If explorer is not manually refreshed during the test run, progress bar shows 100% constantly
As title says,
during the test if the progress bar is not refreshed manually (e.g. by hitting F5) the progress bar show 100% constantly (attached screenshot, with refreshed explorer tab on the right)
Screenshot 2019-06-25 at 23 06 29

### PR DESCRIPTION
**Pull request by laszlourszuly**
Fixes: #72

### CODE REVIEW

**Comment by blenessy** [comment]
@MuncleUscles could you please review this on my behalf ?

**Review by MuncleUscles — APPROVED** [review]

**Review by blenessy — APPROVED** [review]
@swiec please test then approve & merge if happy.

**Comment by laszlourszuly** [comment]
Any input on this @swiec before merging to master?

**Review by swiec — COMMENTED** [review]
tested on integration branch. Please merge to master

**Pull request merged**
